/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, PaymentMethod } from "@prisma/client";

export class PaymentMethodServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.PaymentMethodCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentMethodCountArgs>
  ): Promise<number> {
    return this.prisma.paymentMethod.count(args);
  }

  async paymentMethods<T extends Prisma.PaymentMethodFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentMethodFindManyArgs>
  ): Promise<PaymentMethod[]> {
    return this.prisma.paymentMethod.findMany(args);
  }
  async paymentMethod<T extends Prisma.PaymentMethodFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentMethodFindUniqueArgs>
  ): Promise<PaymentMethod | null> {
    return this.prisma.paymentMethod.findUnique(args);
  }
  async createPaymentMethod<T extends Prisma.PaymentMethodCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentMethodCreateArgs>
  ): Promise<PaymentMethod> {
    return this.prisma.paymentMethod.create<T>(args);
  }
  async updatePaymentMethod<T extends Prisma.PaymentMethodUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentMethodUpdateArgs>
  ): Promise<PaymentMethod> {
    return this.prisma.paymentMethod.update<T>(args);
  }
  async deletePaymentMethod<T extends Prisma.PaymentMethodDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentMethodDeleteArgs>
  ): Promise<PaymentMethod> {
    return this.prisma.paymentMethod.delete(args);
  }
}
